name: build check
on: [pull_request, workflow_dispatch, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.1

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - run: pnpm install

      - run: pnpm run lint
      - run: pnpm run test:unit
      - run: pnpm run build

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          project: ./apps/web-e2e
          start: pnpm run preview
          browser: chrome

      - name: lighthouse check
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: 'lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: apps/web/out/
