name: spa-ci

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: pnpm install
      - run: pnpm run test:static
      - uses: cypress-io/github-action@v5
        with:
          project: ./apps/web-e2e
          start: pnpm run preview
          browser: chrome
